Manage E_DEPRECATED
pear/DB pull request #27
Opened 2024-01-17 08:18 UTC by remicollet

raised with 8.3 in pear.php

2024-02-29 15:29 UTC, MarkMaldaba commented on tests/db_error2.phpt
> +            // Ignore E_STRICT notices unless they have been turned on
Copy/paste error: `E_DEPRECATED`

2024-03-09 20:12 UTC, ashnazg commented on tests/db_error2.phpt
> +            // Ignore E_STRICT notices unless they have been turned on
What error?  They all look spelled correct to me... ?

2024-03-09 22:11 UTC, MarkMaldaba commented
```
// Ignore E_STRICT notices unless they have been turned on
          ^^^^^^^
```

2024-03-09 22:12 UTC, MarkMaldaba commented on tests/db_error2.phpt
> +            // Ignore E_STRICT notices unless they have been turned on
```
// Ignore E_STRICT notices unless they have been turned on
          ^^^^^^^
```

2024-03-10 15:10 UTC, ashnazg requested changes

2024-03-10 15:10 UTC, ashnazg commented on tests/db_error2.phpt
> +            // Ignore E_STRICT notices unless they have been turned on
Ah, I see now... I had interpreted `E_DEPRECATED` as a _subset_ of `E_STRICT` just looking at the small diff context around this change, but now I can see there is a similar condition block for `E_STRICT` itself.

@remicollet , could up correct this comment?

2024-03-11 07:33 UTC, remicollet commented on tests/db_error2.phpt
> +            // Ignore E_STRICT notices unless they have been turned on
fixed

2024-03-12 01:02 UTC, ashnazg approved these changes

2024-03-13 17:53 UTC, merged