each() deprecated in PHP 7.2
pear/DB pull request #8
Opened 2019-05-07 20:44 UTC by arcticlinux

Not sure if there is any interest in fixing this, but each() has been deprecated in PHP 7.2

2019-05-08 18:37 UTC, mpdude commented
👍🏻

2019-10-18 04:09 UTC, CloCkWeRX commented on DB/storage.php
> +        foreach($rowdata as $key => $value) {
foreach (

2019-10-18 05:13 UTC, CloCkWeRX requested changes
Mergable with the minor CS style fix

2019-11-02 20:56 UTC, mpdude commented
@arcticlinux could you fix CS so we could get this merged?

2020-04-19 19:28 UTC, ashnazg approved these changes

2020-04-19 19:28 UTC, merged